config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :batting_averages, only: %i[index new] do
    collection do
      post :import_csv_data
    end
  end
  root 'batting_averages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batting_average.rb
class BattingAverage < ApplicationRecord
  validates :player_id, uniqueness: { scope: :year_id }

  default_scope { order(average: :desc) }
  scope :search_by_player_id, lambda { |player_id| where("player_id LIKE CONCAT('%',?,'%')", player_id&.downcase) }
  scope :search_by_year, lambda { |year| where(year_id: year) }

  def self.import(file_path)
    CSV.foreach(file_path, headers: true) do |row|
      item = {}
      row = row.to_hash
      item[:player_id] = row['playerID']
      item[:year_id] = row ['yearID']
      item[:team_name] = row['teamID']
      item[:average] = calculate_average(row['H']&.to_d, row['AB']&.to_d)

      BattingAverage.find_or_create_by(item)
    end
  end

  def self.calculate_average(h, ab)
    return 0 if h.eql?(0) || ab.eql?(0) || h.nil? || ab.nil?

    h / ab
  end

  def self.fetch_years
    BattingAverage.unscoped.select('DISTINCT year_id').map(&:year_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/batting_averages_controller.rb
class BattingAveragesController < ApplicationController
  def index
    @batting_averages = fetch_averages
  end

  def new; end

  def import_csv_data
    ImportBattingDataFromCsvJob.perform_later("#{Rails.root}/public/Batting.csv") if params[:file].present?
    redirect_to root_path
  end

  private

  def fetch_averages
    averages = BattingAverage.all
    averages = averages.search_by_player_id(params[:player_id]) if params[:player_id].present?
    averages = averages.search_by_year(params[:year_id]) if params[:year_id].present?
    averages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batting_averages_helper.rb
module BattingAveragesHelper
  def average_present?
    BattingAverage.any?
  end
end

app/views/batting_averages/index.html.erb
<% unless average_present? %>
  <div class="container m-5">
    Please upload CSV <%= link_to 'here', new_batting_average_path %> <br>Or
    Please refresh the page and check after sometime.
  </div>
<% else %>
  <nav class="navbar navbar-light bg-light">
    <%= form_tag batting_averages_path, class: 'form-inline', method: :get do %>
      <%= text_field_tag 'player_id', params[:player_id], placeholder: "Enter player id", class: 'form-control mr-sm-2' %>
      <%= select_tag 'year_id', options_for_select(BattingAverage.fetch_years, params[:year_id]), { prompt: "Year", class: "form-control mr-sm-2" } %>
      <%= submit_tag 'Search!', class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
  </nav>
  <div class="container mt-5">
    <h1 class="text-center">Batting Averages</h1>
    <table class="table table-striped text-center">
      <thead>
        <td>PlayerID</td>
        <td>Team name</td>
        <td>YearID</td>
        <td>Batting Average </td>
      </thead>
      <% @batting_averages.each do |batting_average| %>
      <tr>
        <td><%= batting_average.player_id %></td>
        <td><%= batting_average.team_name %></td>
        <td><%= batting_average.year_id %></td>
        <td><%= batting_average.average %></td>
      </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/batting_averages/new.html.erb
<div class="container mt-5">
  <h2 class="card card-header">Import CSV</h2>
  <%= form_tag import_csv_data_batting_averages_path, multipart: true, class: 'card card-body' do %>
    <%= file_field_tag :file, class: 'form-control' %>
    <%= submit_tag "Import CSV", class: 'btn btn-primary mt-1' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BattingAverages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>